name: Nintendo Switch

on:
  push:
    branches: [ foreve, 1.2.0 ]
  pull_request:
    branches: [ foreve, 1.2.0 ]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: devkitpro/devkita64:20200730
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: make clean
      run: make PLATFORM=Switch clean
    - name: make 
      run: make PLATFORM=Switch
    - name: Create directory structure
      run: |
        mkdir -p bin/switch/sonicforever
        mv bin/Switch/sonicforever.nro bin/switch/sonicforever
        mkdir -p bin/switch/sonic2absolute
        mv bin/Switch/sonic2absolute.nro bin/switch/sonic2absolute
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: bin/Switch/sd
